- name: Restart only app (handler)
  become: yes
  ansible.builtin.shell: |
    cd {{ deploy_path }}
    sudo podman-compose stop app
    sudo podman-compose rm app
    sudo podman-compose up app -d --build
  args:
    chdir: "{{ deploy_path }}"